spring.application.name=care-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/care_db
spring.datasource.username=postgres
spring.datasource.password=Sheha

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=care-super-secret-key-for-development-only-change-this-2026-care-project-jwt
jwt.expiration=86400000
